In [7]:
import numpy as np #alias
arr = np.array([[1,2,4,3],[4,6,5,3]])
print(arr)
print(type(arr))
arr.ndim


[[1 2 4 3]
 [4 6 5 3]]
<class 'numpy.ndarray'>


2

In [8]:
arr = np.array(30)
arr.ndim

0

In [14]:
arr = np.array([[[[]]]])

# arr.ndim

arr.shape

(1, 1, 1, 0)

In [17]:
range = np.arange(0,15,2)
range

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [19]:
arr = np.linspace(3,4,5)
arr

array([3.  , 3.25, 3.5 , 3.75, 4.  ])

In [21]:
arr = np.logspace(1,3,7) # start,ending -> powers , 7 ota values iniharu ko bich ma
arr

array([  10.        ,   21.5443469 ,   46.41588834,  100.        ,
        215.443469  ,  464.15888336, 1000.        ])

In [22]:
#np array full of zeros
arr = np.zeros(4)
arr

array([0., 0., 0., 0.])

In [29]:
#to create matrix of element 0
#creating 3*3
arr = np.zeros([3,3,])#rows,column
arr



array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
#we can create tensors with n-dimension that is how many dimension we want
arr = np.zeros([4,2,4])#3-D
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [31]:
#We can create an array with full of ones and matrices as well
arr = np.ones([4,5])
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
#if we want to print elements in int datatype form
arr = np.ones([4,5], dtype= int)
arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [34]:
#if we want to create an array and add element we want
arr = np.full(10,2)#1-D
arr

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [37]:
#2D
arr = np.full([2,4],7)
arr

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [39]:
arr = np.empty([2,3]) #uninitialized array -> without setting any values
arr

array([[5.33948505e-315, 0.00000000e+000, 2.18565567e-312],
       [2.37663529e-312, 2.10077583e-312, 4.99006302e-322]])

In [42]:
arr = np.random.rand(3,3)#-> used to create random floats from 0 to 1
arr

array([[0.5975857 , 0.56043395, 0.53981235],
       [0.33652818, 0.97606575, 0.78316278],
       [0.63703315, 0.16465846, 0.5912862 ]])

In [43]:
arr = np.random.randn(2,1) #-> used to create random floats from normal distribution
arr

array([[1.29228317],
       [0.94091377]])

In [44]:
arr = np.random.randint(12,67)#start,stop
# for random integer
arr

31

In [48]:
arr = np.random.randint(10,110, size = (3,3)) #start,stop,dimension or the no. of values
arr

array([[18, 37, 86],
       [80, 48, 61],
       [70, 30, 36]])