# One Dimensional

In [1]:
import numpy as np

In [2]:
list1 = [1,2,4,7,8,5,9]

In [3]:
a = np.array(list1)
print(a)

[1 2 4 7 8 5 9]


In [4]:
a.size

7

In [5]:
a.shape

(7,)

In [6]:
a.dtype

dtype('int64')

In [10]:
list1 = [1,2,4,7,8.0,5,9.1]
a = np.array(list1)
a.dtype

dtype('float64')

In [12]:
list1 = [1,'2',4,7,8,5,9]
a = np.array(list1)
a.dtype

dtype('<U21')

In [16]:
a = np.zeros(4)
print(a)

[0. 0. 0. 0.]


In [23]:
a = np.full(9,7)
print(a)
type(a)

[7 7 7 7 7 7 7 7 7]


numpy.ndarray

In [25]:
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [27]:
a = np.random.rand(3,3)
print(a)

[[0.73150089 0.57521855 0.32341522]
 [0.66967205 0.83674396 0.2816025 ]
 [0.55112331 0.50466517 0.83949706]]


In [28]:
arr = np.random.randn(2,1)
print(arr)

[[0.93617473]
 [1.068019  ]]


In [33]:
arr = np.arange(0,9).reshape((3,3))
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [43]:
a = np.array([1,5,3,2,5])
print(a)

[1 5 3 2 5]


In [44]:
a.dtype

dtype('int64')

In [45]:
a.itemsize

8

In [46]:
a.size

5

# Indexing

In [47]:
print(a[0])

1


In [48]:
print(a[-1])

5


In [50]:
print(a[0])

1


# Slicing

In [51]:
print(a[1:3])

[5 3]


In [53]:
print(a[::-1])

[5 2 3 5 1]


In [54]:
print(a[1:5:2])

[5 2]


# Arithmetic Operations

In [55]:
a = np.array([1,4,3])
b = np.array([2,4,3])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a % b)
print(a @ b)

[3 8 6]
[-1  0  0]
[ 2 16  9]
[0.5 1.  1. ]
[0 1 1]
[1 0 0]
27


# Statistical operations

In [3]:
print(np.max(a))
print(np.min(a))
print(np.sum(a))
print(np.var(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))